# Uncomment the next line to define a global platform for your project
platform :ios, '7.0'

target 'Example' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    use_frameworks!

    # Pods for Example
    
    pod 'MSWebController', :path=> '../'
    
    target 'ExampleTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    target 'ExampleUITests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end
